# Generated by Django 5.0.6 on 2024-05-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weather', models.CharField(choices=[('Tropical', 'Tropical'), ('Seco', 'Seco'), ('Templado', 'Templado'), ('Continental', 'Continental'), ('Fríos', 'Fríos'), ('Cualquiera', 'Cualquiera')], default='Cualquiera', max_length=12)),
                ('image', models.ImageField(upload_to='cultivos/')),
                ('quantity', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('Principiante', 'Principiante'), ('Medio', 'Medio'), ('Difícil', 'Difícil')], default='Principiante', max_length=12)),
                ('season', models.CharField(choices=[('Primavera', 'Primavera'), ('Verano', 'Verano'), ('Otoño', 'Otoño'), ('Invierno', 'Invierno')], default='Primavera', max_length=9)),
            ],
        ),
    ]
